spring:
  profiles:
    active: dev
    include: secret
  mail:
    host: smtp.gmail.com
    port: 587
    username: jhseodevelopment@gmail.com
    password: PASSWORD_SECRET
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            logging:
              level:
                org.springframework.mail: DEBUG